# Database configuration file

development:
  adapter: postgresql
  database: your_app_development
  username: your_username
  password: your_password
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: your_app_test
  username: your_username
  password: your_password
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: your_app_production
  username: your_username
  password: your_password
  host: your_production_host
  port: 5432
  pool: 15
  timeout: 5000
